### ISSUE TITLE
Do not report RESPONSE_BODY_VALIDATION_ERROR when a required field is not present in a response example

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#156]
We could address issue https://github.com/Azure/azure-rest-api-specs/issues/755 on the model validation tool, so that we don't report noise. Relaxing the "require" constraint for response models.
Catching cases where GET->PUT cycle is broken may need to be done in another way (potentially a linter rule) which would specifically flag this problem.

**Comment by sergey-shandar** [comment]
Another case https://github.com/Azure/azure-rest-api-specs-pr/pull/192

**Comment by vishrutshah** [comment]
un-assigning as my focus would on https://github.com/Azure/oav/issues/142 for next sprint.

**Comment by veronicagg** [comment]
@amarzavery do you have any thoughts on this one? does "require" really apply to responses? how would we model cases in which a property is required for the request but not the response, creating another model for it, seems a bit too much.

**Comment by amarzavery** [comment]
I primarily do not agree with this issue. Please do not look at it from SDK point of view. The focus is to ensure that the example matches the model definition in the swagger spec. If the spec says that the property is required then the service should obey that. 

> The primary aim of this tool is to validate that the swagger matches the wire format.


>how would we model cases in which a property is required for the request but not the response, creating another model for it, seems a bit too much.

For sensitive properties like `password` or `ssh keys`, that could be `required` in the request but the server sends null in the response then such properties should be marked as `"x-nullable": true`. When we handle the nullable thing in #155 then this scenario will be automatically covered.

Customers using the REST API / SDK would rely on the required property of the model and would get screwed.

For example:
In a pageable response, the "value" property of type array is a required property. The "nextLink" property may or may not be present. What would happen if the server decides to not send the value property if the array is empty? This will break our deserialization logic in all the Autorest generated SDKs because we flatten the "value" property and return an IEnumerable<T> or IPageable<T>.

**Comment by matthchr** [comment]
@amarzavery - Amar, suggesting the use of `x-nullable` breaks the "required-ness" on the request. Making the property optional on the request means customers are going to be more likely to omit it.

This is maybe a more generic problem than passwords and other sensitive information, as there can be other types of things which are required in some contexts and omitted in others... but at least right now, marking these fields required in the Swagger generates the correct client code (which doesn't blow up even when the field is omitted on a get).

**Comment by vladbarosan** [comment]
stale and not relevant anymore
