### ISSUE TITLE
Is it possible to get the filename of the example in the message when it fails?

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/oav#213]
For example: 
``` haskell
{ code: 'RESPONSE_VALIDATION_ERROR',
  id: 'OAV108',
  message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Update a node" in operation "DscNode_Update".',
  innerErrors: 
   [ { code: 'INVALID_RESPONSE_BODY',
       errors: 
        [ { code: 'OBJECT_ADDITIONAL_PROPERTIES',
            params: [ [ 'name', 'id' ] ],
            message: 'Additional properties not allowed: name,id',
            path: [],
            description: 'Definition of the dsc node type.' } ],
       message: 'Invalid body: Additional properties not allowed: name,id',
       path: [] } ] }
error: Found errors in validating the response with statusCode "200" for x-ms-example "List DSC nodes by Automation Account" in operation "DscNode_ListByAutomationAccount".:
```

We already get 
- the example name:  `List DSC nodes by Automation Account` 
- the operation name: `DscNode_ListByAutomationAccount`

But it would be nice to know which file the actual example is in, so we can find it with less effort.

**Comment by amarzavery** [comment]
## Prior Context:
We resolve the spec completely by resolving the external references. So the `"x-ms-examples": {}` contains the description of the example and the value of the resolved example from the external file. 
Thus the file path from which the example came is lost. We had to do this, because `sway` (external module that we depend on) has bugs in resolving external and circular references. Hence we resolve the entire file and give it to sway.

## A possible solution:
We should **definitely not** change the spec. However, we can maintain an internal data structure in lib/specValidator.js that can maintain a mapping like this:
```json5
{ 
  "StorageAccounts_CreateOrUpdate": {   //operationId
     "x-ms-examples": {  //actual x-ms-example as-is
         "creating a storage account" :  {
            "$ref": "../examples/creatingStorageAccount.json"
        }
     }
}
```

Then while validating the example we can use this mapping to provide the file path in case there is an error.


**Note:** We should enable this by having an optional setting called `createxmsExampleFilePathMaper` that is disabled by default. It should only be enabled for model validation. We do not need this for `semantic validation` and `live validation`. This saves time and memory for modes that do not require this information.

**Comment by vladbarosan** [comment]
solved with source mapping
