### ISSUE TITLE
OAV failed with INTERNAL_ERROR

### ISSUE THREAD

**Issue by yungezz** [Azure/oav#449]
Related PR: 
https://github.com/Azure/azure-rest-api-specs/pull/6601

Error detail:
```
error: 
{ code: 'INTERNAL_ERROR',
  id: 'OAV100',
  message:
   'internal error: Failed to load a reference file specification/logic/resource-manager/Microsoft.Logic/stable/2019-05-01/. (Error: EISDIR: illegal operation on a directory, read)',
  innerErrors:
   [ { message:
        'internal error: Failed to load a reference file specification/logic/resource-manager/Microsoft.Logic/stable/2019-05-01/. (Error: EISDIR: illegal operation on a directory, read)',
       code: 'INTERNAL_ERROR',
       id: 'OAV100',
       innerErrors: [Array] } ] }

```

**Comment by visharm** [comment]
I am not sure where is this error coming from? Why it is failing to load this directory. This is the new version I have added. I have asked for help to fix this error. Do you know what the issue is?

**Comment by raych1** [comment]
@visharm, it's due to there's an incorrect $ref value set to `"$ref" : "/#definitions/ApiOperationPropertiesDefinition"` which is resolved as local reference.

For OAV, we could add validation on the path to referenced file [refDetails.uri](https://github.com/Azure/oav/blob/b25a7827cf1f00dfcac906f1dc0f029b3bd26100/lib/validators/specResolver.ts#L332)

**Comment by yungezz** [comment]
another instance of internal error: https://github.com/Azure/azure-rest-api-specs/pull/7246/files. not sure whether this is same OAV issue or different one.

**Comment by raych1** [comment]
@yungezz , this issue was fixed and I tried to repro with your referenced PR. Oav validation passes locally.
