### ISSUE TITLE
Response containing an openapi spec in the 200 body is not supported

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#91]
Here's the CI job https://travis-ci.org/Azure/azure-rest-api-specs/jobs/219903910#L2093
The 200 response of an operation is returning an openapi spec, there is a reference to a definition inside that "body" and it's not resolving properly, therefore failing CI.

**Comment by amarzavery** [comment]
```
error: Errors
error: ------
error:  
{ code: 'SEMANTIC_VALIDATION_ERROR',
  message: 'The spec https://raw.githubusercontent.com/shimedh/azure-rest-api-specs/e25c224942404167481479cac1a8d0bde1559732/arm-logic/2016-06-01/swagger/logic.json has semantic validation errors.',
  innerErrors: 
   [ { code: 'UNRESOLVABLE_REFERENCE',
       message: 'Reference could not be resolved: #/definitions/request-simpleManualTrigger',
       path: 
        [ 'paths',
          '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Logic/workflows/{workflowName}/listSwagger',
          'post',
          'x-ms-examples',
          'Get OpenAPI definition for the workflow',
          'responses',
          '200',
          'body',
          'paths',
          '/simpleManualTrigger/paths/invoke',
          'post',
          'parameters',
          '4',
          'schema',
          '$ref' ],
       error: 'JSON Pointer points to missing location: #/definitions/request-simpleManualTrigger' } ] }
```

The error is coming from Sway. We are calling Sway to validate the spec semantically like this `let validationResult = self.swaggerApi.validate();` over [here](https://github.com/Azure/openapi-validation-tools/blob/master/lib/specValidator.js#L154). Since we resolve all the relative references, before calling Sway, x-ms-examples are in place. [This thing](https://github.com/Azure/azure-rest-api-specs/pull/1102/files#diff-f89ff2555ec39341b2d8343cfb1d4b4dR61)  messes up the semantic validator.

Will have to think out of the box to resolve this scenario.

**Comment by amarzavery** [comment]
Once the tool fixes the bug, we need to put the reference to x-ms-example back in the swagger spec

**Comment by veronicagg** [comment]
is this the same as https://github.com/Azure/oav/issues/152 ?

**Comment by amarzavery** [comment]
@veronicagg - that is true.

**Comment by amarzavery** [comment]
@veronicagg - sorry this is different than the problem faced in #152. This issue is about semantic validation. Whereas the other issue is about model validation.

As per this issue, the response body in the example itself is a json document/swagger spec with references ` "$ref": "#/definitions/request-simpleManualTrigger"`.

So we need to make the local references in the example file as inline definition and then give it to the validator to validate.

**Comment by veronicagg** [comment]
@amarzavery ah ok, is this something you'd like to take a look at?

**Comment by amarzavery** [comment]
Keep it in the backlog for now. If I have time I will pick it up.

**Comment by vladbarosan** [comment]
stale not relevant anymore
