### ISSUE TITLE
oav generate-examples generated min and max sets with same title

### ISSUE THREAD

**Issue by gaagarwalMS** [Azure/oav#935]
The generated examples have the same title value for both the min and max set for every operation. So, the `cadl compile` links (with the `x-ms-examples`) just one of them in the generated swagger as the other one gets override.

Both the titles in the min and the max set example files should have different titles (maybe with a suffix like _min or _max) so that the CADL links them properly to the swagger during compilation.

**Comment by bhaden94** [comment]
Still seeing this issue, which is requiring us to manually update all our generated examples.

**Comment by dargilco** [comment]
+1 Still seeing this issue. When I use the tool with my TypeSpec project in azure-rest-api-specs to auto-generate examples, validation fails (locally when running `npx tsv .` or in CI/CD pipeline), saying a swagger title is used in multiple examples. I have to write a script to edit all the auto-generated swagger examples (there could be many!) to make sure each one has a unique title in order to get a green build of my TypeSpec. This should be an easy tool fix in OAV. Please fix this.

**Comment by mikeharder** [comment]
@dargilco: Can you please add instructions to reproduce the issue?

**Comment by dargilco** [comment]
Repro steps:

- Open a console window at the root of your azure-rest-api-specs clone
- git checkout dargilco/azure-ai-client
- cd specification\ai\data-plane\Azure.AI.Client\preview\2024-07-01-preview
- oav generate-examples azure-ai-client.json

Look at any generated _MaximumSet and _MinimumSet swagger example, and notice they have the same value for "title" at the top.
For example, look at these two:
type examples\Evaluations_DeleteSchedule_MaximumSet_Gen.json
type examples\Evaluations_DeleteSchedule_MinimumSet_Gen.json
They both have the title "Evaluations_DeleteSchedule",

If you try to commit those files to a TypeSpec PR, the pipeline will error out pointing out all the titles that are used in more than one example swagger.

I don't know of an easy way right now to show this error locally.

**Comment by dargilco** [comment]
Also, unrealted, note that I need to run the `npx prettier --write .\Endpoints_ListSecrets_MaximumSet_Gen.json` on each one of the examples, since the auto-generated example is not formatted correctly according to validation checks in the TypeSpec PR CI/CD pipeline. I'll open a separate GitHub issue on that.

**Comment by mikeharder** [comment]
Working on a fix

**Comment by dargilco** [comment]
Thank you @mikeharder, I appreciate it!
