### ISSUE TITLE
RPC-Async-V1-04  provisioningState should be non-terminal state as long as the async operation is in progress.

### ISSUE THREAD

**Issue by leniatgh** [Azure/oav#944]

**Comment by leniatgh** [comment]
@rkmanda Does this rule apply to provisioningState+200/201 pattern only? or it applies to location/AzureAsyncOperation+202 as well?

 - If we only consider provisioningState+200/201 pattern, this rule seems to validate provisioningState value must be `*ing` instead of `*ed`.
 - Is `Accepted` terminal or non-terminal state?
 - We could asset provisioningState is non-terminal state in *initial response* of LRO, but is this sufficient?

**Comment by rkmanda** [comment]
@leni-msft This rule applies to long running PUT, PATCH, DELETE operations which are expected to modify the provisioningState property during the lifetime of the long-running operation. Terminal states for async operations are Succeeded or Failed. I guess the best we can do is to detect that whenever the initial response of these operations indicates its a long-running operation, the immediate GET of the resource Should have the provisioningState property set to a non-terminal state. 

There is a danger if the long running operation completes very quickly we might see that the provisioningState property has flipped to a terminal state on the GET but I guess this would be rare. If at all this test fails too many times because the LRO is too quick, we could ask the RP team to self-attest that they have indeed implemented a non-terminal state for provisioning state for all these operations and exempt them from running the test.

Reference - https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#provisioningstate-property
